// #define SPLIT_LAYER_STATE_ENABLE
// #define SPLIT_MODS_ENABLE
// #define SPLIT_ACTIVITY_ENABLE

#define DYNAMIC_KEYMAP_LAYER_COUNT 16

#define RGB_MATRIX_TIMEOUT 600000

#define LAYER_INDICATOR_BRIGHTNESS_INC 22
#define CAPSLOCK_INDICATOR_BRIGHTNESS_INC 76

#define MACCEL_STEEPNESS 1.0 // steepness of accel curve
#define MACCEL_OFFSET 1.0    // X-offset of accel curve
#define MACCEL_LIMIT 6.0     // maximum scale factor
#define MACCEL_DEBUG
#define MACCEL_USE_KEYCODES

#define EECONFIG_USER_DATA_SIZE 20

/* Dilemma-specific features. */
#define DILEMMA_MINIMUM_DEFAULT_DPI 200
#define DILEMMA_DEFAULT_DPI_CONFIG_STEP 100
#define DILEMMA_MINIMUM_SNIPING_DPI 50
#define DILEMMA_SNIPING_DPI_CONFIG_STEP 10

#define SELECT_SOFT_SERIAL_SPEED 4
