#define TAPPING_TERM 200
//#define PERMISSIVE_HOLD
#define QUICK_TAP_TERM_PER_KEY

#define RGB_MATRIX_TIMEOUT 60000
#define ENABLE_COMPILE_KEYCODE

#define POINTING_DEVICE_AUTO_MOUSE_ENABLE
#define AUTO_MOUSE_TIME 800
#define AUTO_MOUSE_DEBOUNCE 50

#undef RGB_MATRIX_DEFAULT_MODE
#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_SOLID_COLOR

#define SPLIT_LED_STATE_ENABLE

#define BILATERAL_COMBINATIONS
// Requires Sunaku's endgame patch - https://github.com/manna-harbour/qmk_firmware/pull/56
#define BILATERAL_COMBINATIONS_LIMIT_CHORD_TO_N_KEYS 4 /* GUI, Alt, Ctrl, Shift */
#define BILATERAL_COMBINATIONS_DELAY_MODS_THAT_MATCH MOD_MASK_GUI
#define BILATERAL_COMBINATIONS_DELAY_MATCHED_MODS_BY 200  /* ms */
#define BILATERAL_COMBINATIONS_ALLOW_CROSSOVER_AFTER 1   /* ms */
#define BILATERAL_COMBINATIONS_ALLOW_SAMESIDED_AFTER 500 /* ms */
#define BILATERAL_COMBINATIONS_TYPING_STREAK_TIMEOUT 160  /* ms */
#define BILATERAL_COMBINATIONS_TYPING_STREAK_MODMASK (~MOD_MASK_SHIFT)

#include "features/config.h"
