#define TAPPING_TERM 200
#define PERMISSIVE_HOLD

#define RGB_MATRIX_TIMEOUT 60000
#define ENABLE_COMPILE_KEYCODE

#define POINTING_DEVICE_AUTO_MOUSE_ENABLE
#define AUTO_MOUSE_TIME 800
#define AUTO_MOUSE_DEBOUNCE 50

#define COMBO_TERM 200
#define EXTRA_SHORT_COMBOS

#undef RGB_MATRIX_DEFAULT_MODE
#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_SOLID_COLOR
