-include $(USER_PATH)/features/rules.mk

SRC += $(USER_PATH)/burkfers.c

TAP_DANCE_ENABLE = yes
CAPS_WORD_ENABLE = no
COMBO_ENABLE = yes
DEFERRED_EXEC_ENABLE = yes

CONSOLE_ENABLE = yes
COMMAND_ENABLE = yes

MOUSEKEY_ENABLE = yes
