TAP_DANCE_ENABLE = yes
CAPS_WORD_ENABLE = no
DEFERRED_EXEC_ENABLE = yes

CONSOLE_ENABLE = yes
COMMAND_ENABLE = yes

MOUSEKEY_ENABLE = yes

ACHORDION_ENABLE = yes

SRC += $(USER_PATH)/burkfers.c

include $(USER_PATH)/features/rules.mk
