#define TAPPING_TERM 400
#define PERMISSIVE_HOLD

#define TAP_CODE_DELAY 50

#define RGB_MATRIX_TIMEOUT 60000
#define ENABLE_COMPILE_KEYCODE

#undef RGB_MATRIX_DEFAULT_MODE
#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_SOLID_COLOR

#define SPLIT_LED_STATE_ENABLE
#define SPLIT_LAYER_STATE_ENABLE
#define SPLIT_MODS_ENABLE
#define SPLIT_ACTIVITY_ENABLE

#include "features/config.h"
